### ISSUE TITLE
Download example data link fail

### ISSUE THREAD

**Issue by davidxn11** [IBM/AMLSim#20]
The link on the Wiki page to download the example data
[here](https://ibm.box.com/s/iii47drcvpevhpohgrwlrxtcqz8l0wi9)
seems to be broken ("shared file or folder link has been removed or is unavailable to you")
Can this be fixed?
Thanks

**Comment by davidxn11** [comment]
[https://ibm.box.com/s/iii47drcvpevhpohgrwlrxtcqz8l0wi9](url)

**Comment by hkanezashi** [comment]
Sorry, I fixed the sharing link option just now. Would you please try again?

**Comment by davidxn11** [comment]
Thanks - now working

**Comment by proceduralia** [comment]
Hi,
it looks like the link is not working now.

Thank you.
