### ISSUE TITLE
GatherScatterModel bug?

### ISSUE THREAD

**Issue by davidxn11** [IBM/AMLSim#28]
Hi, 
Thanks for adding the new AML typologies!
In GatherScatterModel.java line 91 reads:
   sendTransaction(step, minAmount, orig, bene, isSar, alertID); 
Is this a bug? Should minAmount be replaced with scatterAmount?
In any case line 85 always seems to result in scatterAmount being set to minAmount, so there is never an event when the scatter account gets the 10% margin. Is this the right behavior?
Thanks

**Comment by hkanezashi** [comment]
Thank you for pointing out the bug. Now I fixed it (minAmount -> scatterAmount).
We add several AML typologies, but these are preliminary so we are working on updating documents.
