### ISSUE TITLE
Error in alert config example description?

### ISSUE THREAD

**Issue by youph** [IBM/AMLSim#32]
The description [here](https://github.com/IBM/AMLSim/wiki/Alerts-and-SARs) contains an example of the alert parameter CSV file; the description of the 2nd row `20,fan_in,0,4,6,2700,3000,10,30,,True` reads:
"All alerts are SAR (`is_sar = True`) and all involved accounts are not flagged as SAR."
Should this actually be "... and all involved accounts are flagged as SAR."?

Further, the description of the 3rd row reads:
"All alerts are false-alert (is_sar = False) and all involved accounts are also flagged as SAR"
Should this actually be "... and all involved accounts are **not** flagged as SAR"?

**Comment by hkanezashi** [comment]
Thank you for pointing that out. You are right.
Now I verified these mistakes.
