### ISSUE TITLE
Normal transaction value variation 

### ISSUE THREAD

**Issue by florisviss** [IBM/AMLSim#35]
In all my simulations that I have done all the normal transaction value are between 90 - 110. I cannot find a way to change these normal transaction values, Therefore I was wondering if it is possible to tweak the value of the normal transactions?

thanks in advance,

Floris

**Comment by florisviss** [comment]
Does anyone knows how to accomplish this?

**Comment by Pseudolesss** [comment]
I am also in the same situation than yours. I have just started to use this simulator.

With a quick glance at the code, it seems like the conf.json["default"]["min_account"] parameter changes the average value of normal transaction (used in src\amlsim\SimProperties.java). 

For the variation of the amounts, the conf.json["simulator"]["transaction_interval"] does not seem like it has an impact. 
I'll notify here if I find anything interesting.

**Comment by florisviss** [comment]
Yes exactly the same problem I have. Hope you find a way how to adjust the amounts

**Comment by nelsonjd** [comment]
In conf.json you can adjust these parameters to change the normal transaction values.

```
  "default": {
    "min_amount": 100,
    "max_amount": 1000,
```
...
