### ISSUE TITLE
Networkx MultiDiGraph attribute not found

### ISSUE THREAD

**Issue by aubutt** [IBM/AMLSim#9]
I am using network 1.1 version as stated in Readme. and there is no edge_subgraph method in its documentation.. I tried with g.subgraph() as well but still it remain blank graph.

python scripts/visualize/plot_transaction_graph.py outputs/sampleaml/sampleaml_log.csv 2
Traceback (most recent call last):
  File "scripts/visualize/plot_transaction_graph.py", line 81, in <module>
    g_ = get_alert_graph(g, alertID)
  File "scripts/visualize/plot_transaction_graph.py", line 55, in get_alert_graph
    g_ = g.edge_subgraph(edges)
AttributeError: 'MultiDiGraph' object has no attribute 'edge_subgraph'

**Comment by hkanezashi** [comment]
Thank you for your report.
Sorry, we used `edge_subgraph` function (only in NetworkX version 2.x) by mistake.
We will replace it for version 1.10.

**Comment by hkanezashi** [comment]
I fixed `get_alert_graph` function at `plot_transaction_graph.py`. Would you please try it again?

**Comment by aubutt** [comment]
it worked
